/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsAccordian {
        "panelBody": any;
        "panelTitle": string;
    }
    interface DsButton {
        "disabled": boolean;
        /**
          * Choose the size of the button
         */
        "size": 'small' | 'large';
        /**
          * Which type of button to render
         */
        "type": 'primary' | 'secondary' | 'tertiary';
        /**
          * Whether the button has fixed or autosized with
         */
        "width": 'auto' | 'full';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDsAccordianElement extends Components.DsAccordian, HTMLStencilElement {
    }
    var HTMLDsAccordianElement: {
        prototype: HTMLDsAccordianElement;
        new (): HTMLDsAccordianElement;
    };
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ds-accordian": HTMLDsAccordianElement;
        "ds-button": HTMLDsButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DsAccordian {
        "panelBody"?: any;
        "panelTitle"?: string;
    }
    interface DsButton {
        "disabled"?: boolean;
        /**
          * Choose the size of the button
         */
        "size"?: 'small' | 'large';
        /**
          * Which type of button to render
         */
        "type"?: 'primary' | 'secondary' | 'tertiary';
        /**
          * Whether the button has fixed or autosized with
         */
        "width"?: 'auto' | 'full';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ds-accordian": DsAccordian;
        "ds-button": DsButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-accordian": LocalJSX.DsAccordian & JSXBase.HTMLAttributes<HTMLDsAccordianElement>;
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
