/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsButton {
        "disabled": boolean;
        /**
          * Choose the size of the button
         */
        "size": 'small' | 'large';
        /**
          * Which type of button to render
         */
        "type": 'primary' | 'secondary' | 'tertiary';
        /**
          * Whether the button has fixed or autosized with
         */
        "width": 'auto' | 'full';
    }

}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };


    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "table-component": HTMLTableComponentElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        "disabled"?: boolean;
        /**
          * Choose the size of the button
         */
        "size"?: 'small' | 'large';
        /**
          * Which type of button to render
         */
        "type"?: 'primary' | 'secondary' | 'tertiary';
        /**
          * Whether the button has fixed or autosized with
         */
        "width"?: 'auto' | 'full';
    }

    interface IntrinsicElements {
        "ds-button": DsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
        }
    }
}
